In [78]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import os
from tensorflow.keras.applications import MobileNetV2

In [79]:
from imutils import paths

In [80]:
from tensorflow.keras.layers import MaxPooling2D,Input,Dense,Flatten,Dropout

In [81]:
from tensorflow.keras.models import Model
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam,SGD
from tensorflow.keras.layers import Activation,ReLU,LeakyReLU
from tensorflow.keras.activations import softmax,sigmoid,relu

In [82]:
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split


In [83]:
dataset = 'C:\\Users\\korla\\Downloads\\Open CV project codes\\Face Mask detection\\dataset'
imagepaths = list(paths.list_images(dataset))

In [84]:
len(imagepaths)

3833

In [85]:
imagepaths

['C:\\Users\\korla\\Downloads\\Open CV project codes\\Face Mask detection\\dataset\\without_mask\\0.jpg',
 'C:\\Users\\korla\\Downloads\\Open CV project codes\\Face Mask detection\\dataset\\without_mask\\0_0_aidai_0014.jpg',
 'C:\\Users\\korla\\Downloads\\Open CV project codes\\Face Mask detection\\dataset\\without_mask\\0_0_aidai_0029.jpg',
 'C:\\Users\\korla\\Downloads\\Open CV project codes\\Face Mask detection\\dataset\\without_mask\\0_0_aidai_0043.jpg',
 'C:\\Users\\korla\\Downloads\\Open CV project codes\\Face Mask detection\\dataset\\without_mask\\0_0_aidai_0074.jpg',
 'C:\\Users\\korla\\Downloads\\Open CV project codes\\Face Mask detection\\dataset\\without_mask\\0_0_aidai_0084.jpg',
 'C:\\Users\\korla\\Downloads\\Open CV project codes\\Face Mask detection\\dataset\\without_mask\\0_0_aidai_0136.jpg',
 'C:\\Users\\korla\\Downloads\\Open CV project codes\\Face Mask detection\\dataset\\without_mask\\0_0_anhu_0004.jpg',
 'C:\\Users\\korla\\Downloads\\Open CV project codes\\Face Mas

In [86]:
data = []
labels = []
for i in imagepaths:
    label = i.split(os.path.sep)[-2]
    labels.append(label)
    image = load_img(i,target_size = (224,224))
    image = img_to_array(image)
    image = preprocess_input(image)
    data.append(image)

C:\Users\korla\Anaconda3\envs\TF\lib\site-packages\PIL\Image.py:963: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  "Palette images with Transparency expressed in bytes should be "


In [87]:
data

[array([[[-0.94509804, -0.9764706 , -0.85882354],
         [-0.94509804, -0.9764706 , -0.85882354],
         [-0.94509804, -0.9764706 , -0.85882354],
         ...,
         [-0.8509804 , -0.90588236, -0.78039217],
         [-0.8509804 , -0.90588236, -0.78039217],
         [-0.84313726, -0.8980392 , -0.77254903]],
 
        [[-0.9137255 , -0.94509804, -0.827451  ],
         [-0.9137255 , -0.94509804, -0.827451  ],
         [-0.9137255 , -0.94509804, -0.827451  ],
         ...,
         [-0.7490196 , -0.8039216 , -0.6784314 ],
         [-0.7490196 , -0.8039216 , -0.6784314 ],
         [-0.7411765 , -0.79607844, -0.67058825]],
 
        [[-0.92156863, -0.9607843 , -0.8039216 ],
         [-0.92156863, -0.9529412 , -0.81960785],
         [-0.92156863, -0.9607843 , -0.8039216 ],
         ...,
         [-0.88235295, -0.8980392 , -0.7882353 ],
         [-0.85882354, -0.8901961 , -0.77254903],
         [-0.85882354, -0.8745098 , -0.7647059 ]],
 
        ...,
 
        [[ 0.38823533, -0.9607843 

In [88]:
labels.count("with_mask")

1915

In [89]:
labels.count("without_mask")

1918

In [90]:
data = np.array(data,dtype='float32')
labels = np.array(labels)

In [91]:
data

array([[[[-0.94509804, -0.9764706 , -0.85882354],
         [-0.94509804, -0.9764706 , -0.85882354],
         [-0.94509804, -0.9764706 , -0.85882354],
         ...,
         [-0.8509804 , -0.90588236, -0.78039217],
         [-0.8509804 , -0.90588236, -0.78039217],
         [-0.84313726, -0.8980392 , -0.77254903]],

        [[-0.9137255 , -0.94509804, -0.827451  ],
         [-0.9137255 , -0.94509804, -0.827451  ],
         [-0.9137255 , -0.94509804, -0.827451  ],
         ...,
         [-0.7490196 , -0.8039216 , -0.6784314 ],
         [-0.7490196 , -0.8039216 , -0.6784314 ],
         [-0.7411765 , -0.79607844, -0.67058825]],

        [[-0.92156863, -0.9607843 , -0.8039216 ],
         [-0.92156863, -0.9529412 , -0.81960785],
         [-0.92156863, -0.9607843 , -0.8039216 ],
         ...,
         [-0.88235295, -0.8980392 , -0.7882353 ],
         [-0.85882354, -0.8901961 , -0.77254903],
         [-0.85882354, -0.8745098 , -0.7647059 ]],

        ...,

        [[ 0.38823533, -0.9607843 , -0

In [92]:
labels

array(['without_mask', 'without_mask', 'without_mask', ..., 'with_mask',
       'with_mask', 'with_mask'], dtype='<U12')

In [93]:
sc = LabelBinarizer()
labels = sc.fit_transform(labels)
labels = to_categorical(labels)

In [94]:
labels

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [96]:
data.shape

(3833, 224, 224, 3)

In [95]:
from sklearn.model_selection import train_test_split


In [97]:
 X_train, X_test, y_train, y_test = train_test_split(data, labels, test_size=0.33, random_state=42,stratify=labels)

In [100]:
X_train

array([[[[ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         ...,
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ]],

        [[ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         ...,
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ]],

        [[ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         ...,
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ]],

        ...,

        [[ 1.        ,  1.        ,  1

In [101]:
y_train

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [102]:
X_test

array([[[[-0.27058822, -0.5137255 , -0.73333335],
         [-0.27058822, -0.5137255 , -0.73333335],
         [-0.26274508, -0.5058824 , -0.7254902 ],
         ...,
         [-0.26274508, -0.5294118 , -0.62352943],
         [-0.27843136, -0.54509807, -0.62352943],
         [-0.27843136, -0.54509807, -0.62352943]],

        [[-0.27058822, -0.5137255 , -0.73333335],
         [-0.27058822, -0.5137255 , -0.73333335],
         [-0.26274508, -0.5058824 , -0.7254902 ],
         ...,
         [-0.26274508, -0.5294118 , -0.62352943],
         [-0.27843136, -0.54509807, -0.62352943],
         [-0.27843136, -0.54509807, -0.62352943]],

        [[-0.23137254, -0.47450978, -0.69411767],
         [-0.23137254, -0.47450978, -0.69411767],
         [-0.24705881, -0.49019605, -0.70980394],
         ...,
         [-0.29411763, -0.5764706 , -0.67058825],
         [-0.3333333 , -0.6       , -0.6784314 ],
         [-0.3333333 , -0.6       , -0.6784314 ]],

        ...,

        [[-0.96862745, -0.9843137 , -0

In [103]:
y_test

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [104]:
X_train.shape

(2568, 224, 224, 3)

In [105]:
y_train.shape

(2568, 2)

In [106]:
X_test.shape

(1265, 224, 224, 3)

In [107]:
y_test.shape

(1265, 2)

In [108]:
gene = ImageDataGenerator(rotation_range = 20,zoom_range = 0.15,width_shift_range=0.2,height_shift_range = 0.2,shear_range = 0.15,horizontal_flip = True,vertical_flip=True,fill_mode = 'nearest')

In [109]:
from tensorflow.keras.layers import AveragePooling2D

In [111]:
basemodel = MobileNetV2(weights='imagenet',include_top = False , input_tensor = Input(shape=(224,224,3)))


9412608/9406464 [==============================] - 10s 1us/step


In [112]:
basemodel.summary()

Model: "mobilenetv2_1.00_224"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
Conv1_pad (ZeroPadding2D)       (None, 225, 225, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 112, 112, 32) 864         Conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 112, 112, 32) 128         Conv1[0][0]                      
_______________________________________________________________________________

In [114]:
mainmodel = basemodel.output
mainmodel = AveragePooling2D(pool_size = (7,7))(mainmodel)
mainmodel = Flatten(name='Flatten')(mainmodel)
mainmodel = Dense(128,activation = 'relu')(mainmodel)
mainmodel = Dropout(0.5)(mainmodel)
mainmodel = Dense(2,activation='softmax')(mainmodel)

model = Model(inputs = basemodel.input,outputs = mainmodel)


In [117]:
for layer in basemodel.layers:
    layer.trainable = False

In [118]:
model.summary()

Model: "functional_3"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
Conv1_pad (ZeroPadding2D)       (None, 225, 225, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 112, 112, 32) 864         Conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 112, 112, 32) 128         Conv1[0][0]                      
_______________________________________________________________________________________

Total params: 2,422,210
Trainable params: 164,226
Non-trainable params: 2,257,984
__________________________________________________________________________________________________


In [121]:
from tensorflow.keras.optimizers import Adam

In [126]:
learning_rate = 0.001
Epochs = 30
batches = 12
opt = Adam(lr = learning_rate , decay = learning_rate/Epochs)
model.compile(loss = 'binary_crossentropy',optimizer=opt,metrics = ['accuracy'])
model.fit(
    gene.flow(X_train,y_train,batch_size = 12),
    steps_per_epoch = len(X_train)//batches,
    validation_data = (X_test,y_test),
    validation_steps = len(X_test)//batches,
    epochs = Epochs


)




model.save(r'C:\Users\korla\Desktop\projects_ME\open CV\Face Mask Detection\saving path\mobilenet_v2.model')

Epoch 1/30
214/214 [==============================] - 464s 2s/step - loss: 0.1835 - accuracy: 0.9283 - val_loss: 0.0830 - val_accuracy: 0.9739
Epoch 2/30
214/214 [==============================] - 427s 2s/step - loss: 0.1068 - accuracy: 0.9622
Epoch 3/30
214/214 [==============================] - 149s 698ms/step - loss: 0.0886 - accuracy: 0.9700
Epoch 4/30
214/214 [==============================] - 225s 1s/step - loss: 0.0649 - accuracy: 0.9762
Epoch 5/30
214/214 [==============================] - 193s 901ms/step - loss: 0.0596 - accuracy: 0.9778
Epoch 6/30
214/214 [==============================] - 191s 891ms/step - loss: 0.0667 - accuracy: 0.9762
Epoch 7/30
214/214 [==============================] - 163s 762ms/step - loss: 0.0759 - accuracy: 0.9731
Epoch 8/30
214/214 [==============================] - 124s 579ms/step - loss: 0.0541 - accuracy: 0.9809
Epoch 9/30
214/214 [==============================] - 113s 527ms/step - loss: 0.0334 - accuracy: 0.9883
Epoch 10/30
214/214 [==========

In [127]:
y_test_pred = model.predict(X_test,batch_size = batches)


In [129]:
y_test_pred = np.argmax(y_test_pred,axis=1)

In [130]:
from sklearn.metrics import classification_report

In [131]:
print(classification_report(y_test.argmax(axis=1),y_test_pred,target_names = sc.classes_))

              precision    recall  f1-score   support

   with_mask       0.99      1.00      0.99       632
without_mask       1.00      0.99      0.99       633

    accuracy                           0.99      1265
   macro avg       0.99      0.99      0.99      1265
weighted avg       0.99      0.99      0.99      1265



In [134]:
from sklearn.metrics import confusion_matrix , accuracy_score

In [133]:
confusion_matrix(y_test.argmax(axis=1),y_test_pred)

array([[630,   2],
       [  8, 625]], dtype=int64)

In [136]:
accuracy_score(y_test.argmax(axis=1),y_test_pred) * 100

99.2094861660079