In [31]:
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

In [32]:
from tensorflow.keras.preprocessing.image import img_to_array

In [33]:
from tensorflow.keras.models import load_model

In [34]:
import numpy as np
import cv2
import os 

In [35]:
import time

In [36]:
prototxtpath = os.path.sep.join([r'C:\Users\korla\Desktop\projects_ME\open CV\Face Mask Detection\saving path\mobilenet_v2.model\variables','deploy.prototxt'])

In [37]:
weightspath = os.path.sep.join([r'C:\Users\korla\Desktop\projects_ME\open CV\Face Mask Detection\saving path\mobilenet_v2.model\variables','res10_300x300_ssd_iter_140000.caffemodel'])

In [38]:
prototxtpath

'C:\\Users\\korla\\Desktop\\projects_ME\\open CV\\Face Mask Detection\\saving path\\mobilenet_v2.model\\variables\\deploy.prototxt'

In [39]:
weightspath

'C:\\Users\\korla\\Desktop\\projects_ME\\open CV\\Face Mask Detection\\saving path\\mobilenet_v2.model\\variables\\res10_300x300_ssd_iter_140000.caffemodel'

In [40]:
net = cv2.dnn.readNet(prototxtpath , weightspath)

In [41]:
net

<dnn_Net 000001F8A29E9550>

In [42]:
image = load_model(r'C:\Users\korla\Desktop\projects_ME\open CV\Face Mask Detection\saving path\mobilenet_v2.model')

In [43]:
image1 = cv2.imread(r'C:\Users\korla\Desktop\projects_ME\open CV\Face Mask Detection\example\0_0_0 copy 6.jpg')

In [44]:
image1

array([[[ 87,  92,  93],
        [ 99, 104, 105],
        [108, 113, 114],
        ...,
        [106, 116, 133],
        [109, 119, 136],
        [108, 118, 135]],

       [[ 91,  96,  97],
        [ 97, 102, 103],
        [103, 108, 109],
        ...,
        [109, 117, 134],
        [109, 119, 136],
        [108, 118, 135]],

       [[ 93, 101, 101],
        [ 93, 101, 101],
        [ 97, 105, 105],
        ...,
        [106, 115, 129],
        [110, 119, 133],
        [111, 119, 136]],

       ...,

       [[ 47,  33,  34],
        [ 42,  28,  29],
        [ 40,  27,  25],
        ...,
        [ 32,  23,  19],
        [ 45,  36,  32],
        [ 52,  43,  39]],

       [[ 46,  32,  33],
        [ 42,  28,  29],
        [ 41,  28,  26],
        ...,
        [ 53,  44,  40],
        [ 59,  50,  46],
        [ 57,  48,  44]],

       [[ 44,  30,  31],
        [ 42,  28,  29],
        [ 44,  31,  29],
        ...,
        [ 53,  42,  38],
        [ 58,  47,  43],
        [ 62,  51,  47]]

In [45]:
image1.shape

(551, 383, 3)

In [46]:
h,w = image1.shape[:2]


In [47]:
h,w

(551, 383)

In [48]:
blog = cv2.dnn.blobFromImage(image1,1.0,(300,300),(104.0,177.0,123.0))

In [49]:
blog

array([[[[ -14.,   -3.,    2., ...,    0.,    4.,    4.],
         [  -9.,   -8.,   -3., ...,   -4.,    1.,    3.],
         [ -16.,  -16.,  -15., ...,   -9.,  -12.,  -11.],
         ...,
         [ -63.,  -64.,  -65., ...,  -76.,  -84.,  -74.],
         [ -58.,  -62.,  -67., ...,  -75.,  -67.,  -57.],
         [ -60.,  -62.,  -69., ...,  -56.,  -48.,  -45.]],

        [[ -82.,  -71.,  -66., ...,  -64.,  -59.,  -59.],
         [ -74.,  -73.,  -68., ...,  -69.,  -64.,  -62.],
         [ -80.,  -80.,  -79., ...,  -74.,  -77.,  -77.],
         ...,
         [-152., -152., -153., ..., -158., -166., -153.],
         [-146., -149., -154., ..., -157., -149., -139.],
         [-147., -148., -155., ..., -138., -131., -128.]],

        [[ -27.,  -16.,  -11., ...,    6.,   12.,   12.],
         [ -20.,  -19.,  -14., ...,   -1.,    5.,    9.],
         [ -23.,  -23.,  -22., ...,   -7.,  -10.,   -8.],
         ...,
         [ -97.,  -99., -101., ..., -108., -116., -104.],
         [ -91.,  -96., -1

In [50]:
blog.shape

(1, 3, 300, 300)

In [51]:
net.setInput(blog)

In [52]:
directions = net.forward()

In [62]:
directions

array([[[[0.        , 1.        , 0.9999676 , ..., 1.9832222 ,
          2.980241  , 2.9804547 ],
         [0.        , 1.        , 0.99891233, ..., 2.0086453 ,
          3.7700975 , 2.9615614 ],
         [0.        , 1.        , 0.99842846, ..., 2.009103  ,
          1.9831141 , 2.9634216 ],
         ...,
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ]]]], dtype=float32)

In [60]:

from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model
import numpy as np
import cv2
import os


prototxtPath=os.path.sep.join([r'C:\Users\korla\Desktop\projects_ME\open CV\Face Mask Detection\saving path\mobilenet_v2.model\variables','deploy.prototxt'])
weightsPath=os.path.sep.join([r'C:\Users\korla\Desktop\projects_ME\open CV\Face Mask Detection\saving path\mobilenet_v2.model\variables','res10_300x300_ssd_iter_140000.caffemodel'])



net=cv2.dnn.readNet(prototxtPath,weightsPath)


model=load_model(r'C:\Users\korla\Desktop\projects_ME\open CV\Face Mask Detection\saving path\mobilenet_v2.model')

image=cv2.imread(r'C:\Users\korla\Desktop\projects_ME\open CV\Face Mask Detection\example\with_mask237.jpg')


(h,w)=image.shape[:2]


blob=cv2.dnn.blobFromImage(image,1.0,(300,300),(104.0,177.0,123.0))



net.setInput(blob)
detections=net.forward()


#loop over the detections
for i in range(0,detections.shape[2]):
    confidence=detections[0,0,i,2]
    
    
    if confidence>0.5:
        #we need the X,Y coordinates
        box=detections[0,0,i,3:7]*np.array([w,h,w,h])
        (startX,startY,endX,endY)=box.astype('int')
        
        #ensure the bounding boxes fall within the dimensions of the frame
        (startX,startY)=(max(0,startX),max(0,startY))
        (endX,endY)=(min(w-1,endX), min(h-1,endY))
        
        
        #extract the face ROI, convert it from BGR to RGB channel, resize it to 224,224 and preprocess it
        face=image[startY:endY, startX:endX]
        face=cv2.cvtColor(face,cv2.COLOR_BGR2RGB)
        face=cv2.resize(face,(224,224))
        face=img_to_array(face)
        face=preprocess_input(face)
        face=np.expand_dims(face,axis=0)
        
        (mask,withoutMask)=model.predict(face)[0]
        
        #determine the class label and color we will use to draw the bounding box and text
        label='Mask' if mask>withoutMask else 'No Mask'
        color=(0,255,0) if label=='Mask' else (0,0,255)
        
        #include the probability in the label
        label="{}: {:.2f}%".format(label,max(mask,withoutMask)*100)
        
        #display the label and bounding boxes
        cv2.putText(image,label,(startX,startY-10),cv2.FONT_HERSHEY_SIMPLEX,0.45,color,2)
        cv2.rectangle(image,(startX,startY),(endX,endY),color,2)
        
        
        
cv2.imshow("OutPut",image)
cv2.waitKey(0)
cv2.destroyAllWindows()